env:
  TERM: xterm-256color

window:
  padding:
    x: 4
    y: 4
  decorations: buttonless 

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false

cursor_style: Block

font:
  normal:
    family: JetBrains Mono
  size: 15

key_bindings:
  - { key: Left,     mods: Option, chars: "\x1b[1;5D"                   }
  - { key: Right,    mods: Option, chars: "\x1b[1;5C"                   }

background_opacity: 0.97

blur: 5

